import { useEffect, useRef, useState } from 'react'
import { Archive, ArrowLeft, ArrowRight, ArrowUp, BarChart3, CalendarDays, CheckCheck, Clock3, Download, Expand, Folder, FolderPlus, Inbox, LayoutList, ListTodo, Pause, Pencil, Play, Plus, Search, Settings2, SkipForward, Square, Target, Timer, Trash2, X } from 'lucide-react'
import { WorkspaceHeader } from './Appearance.jsx'
import { useStudy } from './StudyProvider.jsx'
import { addDays, allEntries, clockText, dayStats, durationText, filterTasks, localDay, secondsInDay, taskDepth, timerElapsed } from './studyState.mjs'
const priorityNames={low:'Düşük',normal:'Normal',high:'Yüksek',urgent:'Acil'}
const statusNames={todo:'Yapılacak',doing:'Üzerinde çalışılıyor',done:'Tamamlandı'}
const phaseNames={focus:'Odak zamanı',shortBreak:'Kısa mola',longBreak:'Uzun mola'}
function Field({title,children}){return <label className="field"><span>{title}</span>{children}</label>}
function Modal({title,onClose,children}){const ref=useRef(null);useEffect(()=>{const el=ref.current;el.showModal();return()=>el.close()},[]);return <dialog className="study-modal" ref={ref} onCancel={onClose} onClick={e=>{if(e.target===ref.current)onClose()}}><header><h2>{title}</h2><button className="icon-button" aria-label="Pencereyi kapat" onClick={onClose}><X size={18}/></button></header>{children}</dialog>}
function StudyForm({kind,item={},state,courses,command,onClose}){
 const {error:serverError}=useStudy()
 const [form,setForm]=useState(()=>kind==='task'?{title:'',projectId:state.projects.find(p=>!p.archived)?.id||'',parentId:null,folderId:null,plannedDate:'',dueDate:'',plannedTime:'',estimateMinutes:25,priority:'normal',repeat:'none',tags:[],notes:'',...item}:kind==='project'?{name:'',color:'#39836b',courseId:'',notes:'',...item}:{name:'',projectId:state.projects.find(p=>!p.archived)?.id||'',parentId:null,...item})
 const [error,setError]=useState(''),[saving,setSaving]=useState(false),[tagText,setTagText]=useState((item.tags||[]).join(', '))
 const patch=(key,value)=>setForm(f=>({...f,[key]:value}))
 const folders=state.folders.filter(f=>f.projectId===form.projectId)
 async function save(e){e.preventDefault();setSaving(true);const next=await command(kind+'.save',{...form,...(kind==='task'?{tags:tagText.split(',').map(t=>t.trim()).filter(Boolean)}:{})});setSaving(false);if(next)onClose();else setError('Kaydedilemedi. Alanları kontrol et; çalışma alanındaki hata mesajına bak.')}
 return <Modal title={(item.id?'Düzenle':'Yeni')+' · '+({task:'Görev',project:'Çalışma projesi',folder:'Klasör'}[kind])} onClose={onClose}><form onSubmit={save} className="study-form">
 <Field title={kind==='task'?'Görev adı':'Ad'}><input autoFocus required maxLength={kind==='task'?240:160} value={form[kind==='task'?'title':'name']} onChange={e=>patch(kind==='task'?'title':'name',e.target.value)} placeholder={kind==='task'?'Örn. Hafta 3 slaytlarını tekrar et':'Örn. Güz dönemi · Biyoloji'}/></Field>
 {kind==='project'?<><div className="study-form-grid"><Field title="Proje rengi"><input type="color" value={form.color} onChange={e=>patch('color',e.target.value)}/></Field><Field title="Bağlı ders · isteğe bağlı"><select value={form.courseId} onChange={e=>patch('courseId',e.target.value)}><option value="">Bağımsız proje</option>{courses.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></Field></div><Field title="Proje notları"><textarea rows={5} maxLength={20000} value={form.notes} onChange={e=>patch('notes',e.target.value)}/></Field></>:
 <><Field title="Çalışma projesi"><select required disabled={Boolean(item.id)||Boolean(item.parentId)} value={form.projectId} onChange={e=>setForm(f=>({...f,projectId:e.target.value,folderId:null,parentId:null}))}><option value="" disabled>Proje seç</option>{state.projects.filter(p=>!p.archived).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Field>
 <Field title={kind==='folder'?'Üst klasör':'Klasör'}><select value={(kind==='folder'?form.parentId:form.folderId)||''} onChange={e=>patch(kind==='folder'?'parentId':'folderId',e.target.value||null)}><option value="">Ana alan</option>{folders.filter(f=>f.id!==item.id).map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></Field>
 {kind==='task'&&<><Field title="Üst görev · isteğe bağlı"><select value={form.parentId||''} onChange={e=>patch('parentId',e.target.value||null)}><option value="">Bağımsız görev</option>{state.tasks.filter(t=>t.projectId===form.projectId&&!t.archived&&t.status!=='done'&&t.id!==form.id).map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select></Field><div className="study-form-grid">
 <Field title="Planlanan gün"><input type="date" value={form.plannedDate||''} onChange={e=>patch('plannedDate',e.target.value)}/></Field><Field title="Planlanan saat"><input type="time" value={form.plannedTime} onChange={e=>patch('plannedTime',e.target.value)}/></Field>
 <Field title="Son tarih"><input type="date" value={form.dueDate||''} onChange={e=>patch('dueDate',e.target.value)}/></Field><Field title="Tahmini süre (dk)"><input type="number" min="0" max="100000" value={form.estimateMinutes} onChange={e=>patch('estimateMinutes',Number(e.target.value))}/></Field>
 <Field title="Öncelik"><select value={form.priority} onChange={e=>patch('priority',e.target.value)}>{Object.entries(priorityNames).map(([k,v])=><option value={k} key={k}>{v}</option>)}</select></Field><Field title="Tamamlandıktan sonra tekrarla"><select value={form.repeat} onChange={e=>patch('repeat',e.target.value)}><option value="none">Tek sefer</option><option value="daily">Her gün</option><option value="weekly">Her hafta</option><option value="monthly">Her ay</option></select></Field></div>
 <Field title="Etiketler · virgülle ayır"><input value={tagText} onChange={e=>setTagText(e.target.value)} placeholder="vize, tekrar, zor konu"/></Field><Field title="Notlar ve kontrol listesi"><textarea rows={5} maxLength={20000} value={form.notes} onChange={e=>patch('notes',e.target.value)} placeholder="Notlarını yaz. Kontrol listesi için her satıra [ ] ekle."/></Field></>}
 </>}
 {error&&<p role="alert" className="study-error">{serverError||error}</p>}<footer><button type="button" className="button ghost" onClick={onClose}>Vazgeç</button><button disabled={saving} className="button primary">{saving?'Kaydediliyor…':'Kaydet'}</button></footer></form></Modal>
}
function EntryForm({task,entry,onClose,command}){
 const {error:serverError}=useStudy()
 const localInput=ms=>{const d=new Date(ms);return localDay(ms)+'T'+String(d.getHours()).padStart(2,'0')+':'+String(d.getMinutes()).padStart(2,'0')}
 const [started,setStarted]=useState(localInput(entry?entry.startedAt*1000:Date.now()-25*60000)),[minutes,setMinutes]=useState(entry?Math.round(entry.seconds/60*100)/100:25),[note,setNote]=useState(entry?.note||''),[error,setError]=useState(''),[saving,setSaving]=useState(false)
 return <Modal title="Çalışma süresi" onClose={onClose}><form className="study-form" onSubmit={async e=>{e.preventDefault();setSaving(true);const result=await command('entry.save',{...(entry?{id:entry.id}:{}),taskId:task.id,startedAt:new Date(started).getTime()/1000,seconds:Number(minutes)*60,note});setSaving(false);if(result)onClose();else setError('Süre kaydedilemedi. Gelecek tarih veya çakışan kayıtları kontrol et.')}}><p>{task.title}</p><Field title="Başlangıç"><input required type="datetime-local" value={started} onChange={e=>setStarted(e.target.value)}/></Field><Field title="Süre (dakika)"><input type="number" required min="0.02" step="0.01" max="1440" value={minutes} onChange={e=>setMinutes(e.target.value)}/></Field><Field title="Not"><input maxLength="2000" value={note} onChange={e=>setNote(e.target.value)}/></Field>{error&&<p className="study-error">{serverError||error}</p>}<footer><button className="button primary" disabled={saving}>Süreyi kaydet</button></footer></form></Modal>
}
function FocusPanel({task,state,now,command,busy,onEdit,onSubtask,onEntry,full,onFull,onClose}){
 const [mode,setMode]=useState('pomodoro'),[minutes,setMinutes]=useState(25)
 const timer=state.timer?.taskId===task.id?state.timer:null,elapsed=timerElapsed(timer,now)
 const total=allEntries(state,now).filter(e=>e.taskId===task.id).reduce((a,e)=>a+e.seconds,0)
 const project=state.projects.find(p=>p.id===task.projectId),children=state.tasks.filter(t=>t.parentId===task.id&&!t.archived)
 const startable=!task.archived&&!project?.archived&&task.status!=='done'
 const currentTimerCommand=action=>command(action,{timerId:timer.id})
 return <aside className={'study-focus panel'+(full?' full':'')} aria-label="Görev ve odak sayacı" data-active-timer={Boolean(timer)}><div className="study-focus-top"><span className="kicker">{project?.name}</span><div><button className="icon-button" aria-label={full?'Listeye dön':'Odak ekranını büyüt'} onClick={onFull}><Expand size={16}/></button><button className="icon-button" aria-label="Görev panelini kapat" onClick={onClose}><X size={16}/></button></div></div>
 <h2>{task.title}</h2><div className="study-focus-clock"><span>{timer?phaseNames[timer.phase]:'Bir sonraki odak adımın'}</span><strong aria-label="Sayaç süresi">{clockText(timer?(timer.targetSeconds?timer.targetSeconds-elapsed:elapsed):mode==='stopwatch'?0:(mode==='pomodoro'?state.settings.focusMinutes:minutes)*60)}</strong><small>{timer?.status==='paused'?'Duraklatıldı':timer?.status==='finished'?'Bu aralık tamamlandı':timer?.status==='running'?'Sayaç çalışıyor':'Hazır olduğunda başla'}</small>
 {timer?.targetSeconds&&<progress max={timer.targetSeconds} value={elapsed} aria-label="Oturum ilerlemesi"/>}</div>
 {!timer&&startable&&<div className="study-timer-modes"><select aria-label="Sayaç türü" value={mode} onChange={e=>setMode(e.target.value)}><option value="pomodoro">Pomodoro</option><option value="stopwatch">Kronometre</option><option value="countdown">Geri sayım</option></select>{mode==='countdown'&&<input aria-label="Geri sayım dakikası" type="number" min="1" max="720" value={minutes} onChange={e=>setMinutes(Number(e.target.value))}/>}</div>}
 <div className="study-focus-actions">{!timer&&startable?<button className="button primary" disabled={busy} onClick={()=>command('timer.start',{taskId:task.id,mode,minutes})}><Play size={18}/> Odaklanmaya başla</button>:timer?.status==='finished'?<>{timer.mode==='pomodoro'&&<button className="button primary" disabled={busy} onClick={()=>currentTimerCommand('timer.next')}><Play size={18}/>{timer.phase==='focus'?'Molayı başlat':'Sonraki odağı başlat'}</button>}<button disabled={busy} className="button ghost" onClick={()=>currentTimerCommand('timer.stop')}>Oturumu kapat</button></>:timer&&<><button className="button primary" disabled={busy} onClick={()=>currentTimerCommand(timer.status==='running'?'timer.pause':'timer.resume')}>{timer.status==='running'?<Pause size={18}/>:<Play size={18}/>} {timer.status==='running'?'Duraklat':'Devam et'}</button><button className="button ghost" disabled={busy} onClick={()=>currentTimerCommand('timer.stop')}><Square size={16}/> Bitir</button>{timer.mode==='pomodoro'&&<button className="button quiet" disabled={busy} onClick={()=>currentTimerCommand('timer.skip')}><SkipForward size={16}/> Aralığı bitir</button>}</>}
 </div>{!timer&&state.timer&&<p className="study-hint">Başlattığında diğer görevin süresi kaydedilir ve sayacı durur.</p>}
 {timer&&<p className="study-hint">{timer.completedFocus} tamamlanan odak · Molalar çalışma süresine eklenmez. Sonraki aralık sen başlatınca çalışır.</p>}
 <div className="study-focus-totals"><span><small>Bu göreve ayrılan</small><b>{durationText(total)}</b></span><span><small>Tahmin</small><b>{task.estimateMinutes} dk</b></span></div>
 <div className="study-detail-actions"><button className="button ghost compact" disabled={busy||task.archived||project?.archived} onClick={onEdit}><Pencil size={15}/> Düzenle</button><button className="button ghost compact" disabled={busy} onClick={onEntry}><Plus size={15}/> Süre ekle</button>{startable&&<button className="button ghost compact" disabled={busy} onClick={onSubtask}><Plus size={15}/> Alt görev</button>}</div>
 {task.notes&&<div className="study-task-notes"><h3>Notlar</h3>{task.notes.split('\n').map((line,i)=>{const check=/^\s*\[([ xX])\]\s*(.*)$/.exec(line);return check?<label key={i}><input type="checkbox" disabled={busy||task.archived||project?.archived} checked={check[1].toLowerCase()==='x'} onChange={()=>{const lines=task.notes.split('\n');lines[i]=(check[1]===' '?'[x] ':'[ ] ')+check[2];command('task.save',{id:task.id,notes:lines.join('\n')})}}/>{check[2]}</label>:<p key={i}>{line||'\u00a0'}</p>})}</div>}
 {children.length>0&&<div className="study-subtasks"><h3>Alt görevler · {children.filter(t=>t.status==='done').length}/{children.length}</h3>{children.map(child=><label key={child.id}><input type="checkbox" disabled={busy||task.archived||project?.archived} checked={child.status==='done'} onChange={()=>command('task.status',{id:child.id,status:child.status==='done'?'todo':'done'})}/>{child.title}</label>)}</div>}
 {task.status!=='done'&&!task.archived&&!project?.archived&&<button className="button ghost" disabled={busy} onClick={()=>command('task.status',{id:task.id,status:'done'})}><CheckCheck size={17}/> Görevi tamamla</button>}
 </aside>
}
function SettingsPanel({state,command,restore}){
 const [values,setValues]=useState(state.settings),[message,setMessage]=useState('')
 return <section className="panel study-settings"><span className="kicker">ÇALIŞMA RİTMİN</span><h2>Sana uygun bir düzen</h2><form onSubmit={async e=>{e.preventDefault();if(await command('settings',{...values,timezoneOffset:-new Date().getTimezoneOffset()}))setMessage('Ayarlar kaydedildi. Yeni süreler bir sonraki aralıkta uygulanır.')}}><div className="study-form-grid">{[['focusMinutes','Odak (dk)',180],['shortBreakMinutes','Kısa mola (dk)',180],['longBreakMinutes','Uzun mola (dk)',180],['longBreakEvery','Uzun molaya kadar odak',12],['dailyGoalMinutes','Günlük çalışma hedefi (dk)',1440]].map(([key,label,max])=><Field key={key} title={label}><input type="number" required min="1" max={max} value={values[key]} onChange={e=>setValues(v=>({...v,[key]:Number(e.target.value)}))}/></Field>)}</div><label className="study-checkbox"><input type="checkbox" checked={values.sound} onChange={e=>setValues(v=>({...v,sound:e.target.checked}))}/> Aralık sonunda ses çal</label><button className="button primary">Ayarları kaydet</button></form>
 <button className="button ghost" onClick={async()=>{try{setMessage('Notification' in window?(await Notification.requestPermission())==='granted'?'Bildirim izni verildi. Tarayıcı açıkken aralık bitişleri bildirilir.':'Bildirim izni verilmedi.':'Bu tarayıcı bildirim desteklemiyor.')}catch{setMessage('Bu ortamda bildirim açılamadı.')}}}>Tarayıcı bildirimlerini aç</button>
 <p className="study-hint">Sayaç sayfa yenilense veya uygulama yeniden açılsa da zaman damgasından devam eder. Pomodoro, belirlenen sürede durur. Kronometre sen durdurana kadar geçen zamanı sayar; bilgisayar uyku süresini de içerebilir. Kayıtlar ekranından süreyi düzeltebilirsin.</p>
 <h3>Yedekleme ve rapor</h3><p>Veriler bu bilgisayarda saklanır. JSON tüm çalışma alanının yedeğidir; CSV kaydedilmiş çalışma oturumlarını içerir.</p><div className="study-inline"><a className="button ghost" href="/api/study/export?format=json"><Download size={16}/> JSON yedeği</a><a className="button ghost" href="/api/study/export?format=csv"><Download size={16}/> CSV raporu</a></div>
 <label className="study-import">JSON yedeğini geri yükle<input type="file" accept=".json,application/json" onChange={async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;if(file.size>10_000_000){setMessage('Yedek en fazla 10 MB olabilir.');return}if(!window.confirm('Yedek mevcut çalışma projeleri, görevler ve sürelerin yerini alacak. Önce JSON yedeğini indirdiğinden emin ol. Devam edilsin mi?'))return;try{if(await restore(JSON.parse(await file.text())))setMessage('Yedek geri yüklendi. Aktif sayaç kapatıldı; yedeklenen süreler korundu.')}catch{setMessage('Dosya geçerli bir JSON yedeği değil.')}}}/></label>{message&&<p role="status" className="study-hint">{message}</p>}
 </section>
}
export default function StudyWorkspace({onClose,initialCourse=null,onOpenCourse}){
 const {state,error,setError,busy,command,refresh,restore,now,setInWorkspace}=useStudy()
 const [view,setView]=useState('today'),[projectId,setProjectId]=useState(''),[folderId,setFolderId]=useState(''),[query,setQuery]=useState(''),[tag,setTag]=useState(''),[showDone,setShowDone]=useState(false),[layout,setLayout]=useState('list')
 const [selected,setSelected]=useState(null),[full,setFull]=useState(false),[form,setForm]=useState(null),[entryForm,setEntryForm]=useState(null),[courses,setCourses]=useState([]),[quick,setQuick]=useState(''),[quickProject,setQuickProject]=useState(''),[planDate,setPlanDate]=useState(localDay()),[reportDate,setReportDate]=useState(localDay()),[dailyNote,setDailyNote]=useState('')
 const quickRef=useRef(null),initialHandled=useRef(false)
 useEffect(()=>{setInWorkspace(true);fetch('/api/study/courses').then(r=>r.json()).then(d=>setCourses(d.courses||[])).catch(()=>{});return()=>setInWorkspace(false)},[])
 useEffect(()=>{if(!state||initialHandled.current)return;initialHandled.current=true;if(initialCourse){const linked=state.projects.find(p=>p.courseId===initialCourse.id&&!p.archived);if(linked){setProjectId(linked.id);setView('project')}else setForm({kind:'project',item:{name:initialCourse.name,courseId:initialCourse.id}})}if(state.timer)setSelected(state.timer.taskId)},[state,initialCourse])
 useEffect(()=>{if(state&&selected&&!state.tasks.some(t=>t.id===selected)){setSelected(null);setFull(false)}if(state&&projectId&&!state.projects.some(p=>p.id===projectId)){setProjectId('');setView('today')}},[state,selected,projectId])
 useEffect(()=>{if(state)setDailyNote(state.dailyNotes[localDay()]||'')},[Boolean(state)])
 useEffect(()=>{const key=e=>{if(/INPUT|TEXTAREA|SELECT|BUTTON/.test(e.target.tagName)||e.target.isContentEditable||document.querySelector('dialog[open]'))return;if(e.key.toLowerCase()==='n'){e.preventDefault();quickRef.current?.focus()}if(e.code==='Space'&&state?.timer){e.preventDefault();const t=state.timer;if(t.status!=='finished')command(t.status==='running'?'timer.pause':'timer.resume',{timerId:t.id})}if(e.key==='Escape'){setFull(false);setSelected(null)}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[state,command])
 if(!state)return <div className="dashboard-shell"><WorkspaceHeader onHome={onClose} current="Çalışma takibi"/><p>{error||'Çalışma alanı yükleniyor…'}</p><button className="button ghost" onClick={refresh}>Yeniden dene</button></div>
 const today=localDay(),activeProjects=state.projects.filter(p=>!p.archived),project=state.projects.find(p=>p.id===projectId),selectedTask=state.tasks.find(t=>t.id===selected)
 const entries=allEntries(state,now),stats=dayStats(state,today,now),filtered=filterTasks(state,{view,projectId,folderId,query,tag,showDone})
 const activeProjectId=projectId||quickProject||activeProjects[0]?.id||''
 const pending=state.tasks.filter(t=>!t.archived&&t.status!=='done'&&!state.projects.find(p=>p.id===t.projectId)?.archived)
 const tags=[...new Set(state.tasks.filter(t=>!t.archived).flatMap(t=>t.tags))].sort()
 function navigate(next,pid=''){setView(next);setProjectId(pid);setFolderId('');setQuery('');setTag('');setFull(false)}
 function taskForm(item={}){if(!activeProjects.length){setForm({kind:'project',item:{}});return}setForm({kind:'task',item:{projectId:activeProjectId,folderId:folderId||null,...(view==='today'?{plannedDate:today}:{}),...item}})}
 async function quickAdd(e){e.preventDefault();if(!quick.trim()||busy)return;if(!activeProjectId){setForm({kind:'project',item:{}});return}const result=await command('task.save',{title:quick,projectId:activeProjectId,folderId:folderId||null,...(view==='today'?{plannedDate:today}:{})});if(result)setQuick('')}
 const totalFor=task=>entries.filter(e=>e.taskId===task.id).reduce((sum,e)=>sum+e.seconds,0)
 function row(task,index,list,compact=false){const parent=state.tasks.find(t=>t.id===task.parentId),p=state.projects.find(p=>p.id===task.projectId);const depth=projectId?taskDepth(state.tasks,task):0;return <article key={task.id} className={'study-task-row'+(task.id===selected?' selected':'')+(task.status==='done'?' is-done':'')} style={{'--depth':Math.min(depth,3)}} draggable={!compact&&!busy} onDragStart={e=>e.dataTransfer.setData('text/plain',task.id)} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();e.stopPropagation();const id=e.dataTransfer.getData('text/plain');if(id&&id!==task.id)command('task.move',{id,otherId:task.id})}}>
 <input className="study-task-check" aria-label={task.title+' tamamlandı'} type="checkbox" checked={task.status==='done'} disabled={busy||task.archived||p?.archived} onChange={()=>command('task.status',{id:task.id,status:task.status==='done'?'todo':'done'})}/>
 <button className="study-task-main" onClick={()=>{setSelected(task.id);setFull(false)}}><strong>{task.title}</strong><span>{!projectId&&<small style={{color:p?.color}}>{p?.name}</small>}{parent&&<small>↳ {parent.title}</small>}{task.priority!=='normal'&&<small className={'study-priority '+task.priority}>{priorityNames[task.priority]}</small>}{task.dueDate&&<small className={task.dueDate<today&&task.status!=='done'?'study-late':''}>Son: {task.dueDate}</small>}{task.repeat!=='none'&&<small>↻</small>}{task.tags.map(t=><small key={t}>#{t}</small>)}</span></button>
 <span className="study-task-time">{durationText(totalFor(task))}<small> / {task.estimateMinutes} dk</small></span>
 {!compact&&<div className="study-row-actions"><button className="icon-button" title="Yukarı taşı" aria-label={task.title+' yukarı taşı'} disabled={busy||index===0} onClick={()=>command('task.move',{id:task.id,otherId:list[index-1].id})}><ArrowUp size={14}/></button><button className="icon-button" title="Düzenle" aria-label={task.title+' düzenle'} disabled={busy||task.archived||p?.archived} onClick={()=>taskForm(task)}><Pencil size={15}/></button><button className="icon-button" title={task.archived?'Geri al':'Arşivle'} aria-label={task.title+(task.archived?' geri al':' arşivle')} disabled={busy||p?.archived} onClick={()=>command('task.archive',{id:task.id,archived:!task.archived})}><Archive size={15}/></button></div>}
 {!task.archived&&!p?.archived&&task.status!=='done'&&<button className="study-task-play" aria-label={task.title+' odaklan'} onClick={()=>{setSelected(task.id);setFull(true)}}><Play size={16}/></button>}</article>}
 const title=project?.name||({today:'Bugünün planı',all:'Tüm görevler',inbox:'Gelen kutusu',week:'Haftalık plan',reports:'Çalışma raporu',logs:'Süre kayıtları',done:'Tamamlananlar',archive:'Arşiv',settings:'Ayarlar'}[view]||'Çalışma alanı')
 const taskViews=['today','all','inbox','project','done','archive']
 const weekStart=addDays(planDate,-((new Date(planDate+'T12:00:00').getDay()+6)%7))
 return <div className="dashboard-shell study-shell"><WorkspaceHeader onHome={onClose} current="Çalışma takibi"/>
 <div className="study-layout"><aside className={'study-sidebar'+(full?' study-hidden':'')}><div className="study-sidebar-title"><span className="study-emblem"><Timer size={23}/></span><div><strong>Çalışma alanım</strong><small>Planla. Odaklan. İlerle.</small></div></div>
 <nav aria-label="Çalışma takibi bölümleri">{[['today',Target,'Bugün'],['inbox',Inbox,'Gelen kutusu'],['all',ListTodo,'Tüm görevler'],['week',CalendarDays,'Haftalık plan'],['reports',BarChart3,'Raporlar'],['logs',Clock3,'Süre kayıtları'],['done',CheckCheck,'Tamamlananlar']].map(([id,Icon,label])=><button key={id} className={view===id&&!projectId?'active':''} onClick={()=>navigate(id)}><Icon size={17}/>{label}{id==='today'&&<small>{filterTasks(state).length}</small>}</button>)}</nav>
 <div className="study-nav-heading"><span>PROJELER</span><button className="icon-button" aria-label="Yeni çalışma projesi" onClick={()=>setForm({kind:'project',item:{}})}><Plus size={16}/></button></div>
 <nav aria-label="Çalışma projeleri">{activeProjects.map(p=><div key={p.id}><button className={projectId===p.id&&!folderId?'active':''} onClick={()=>navigate('project',p.id)}><i style={{background:p.color}}/>{p.name}<small>{pending.filter(t=>t.projectId===p.id).length}</small></button>{projectId===p.id&&state.folders.filter(f=>f.projectId===p.id).map(f=><button key={f.id} className={'study-folder'+(folderId===f.id?' active':'')} onClick={()=>{setFolderId(f.id);setView('project')}}><Folder size={14}/>{f.parentId?'↳ ':''}{f.name}</button>)}</div>)}</nav>
 {!activeProjects.length&&<p className="study-hint">İlk çalışma projenle başla.</p>}<nav className="study-nav-bottom"><button className={view==='archive'?'active':''} onClick={()=>navigate('archive')}><Archive size={17}/> Arşiv</button><button className={view==='settings'?'active':''} onClick={()=>navigate('settings')}><Settings2 size={17}/> Ayarlar ve yedekler</button></nav><small className="study-shortcut">N · Hızlı görev<br/>Boşluk · Duraklat / devam et</small></aside>
 <main className={'study-main'+(full?' study-hidden':'')}>
 <header className="study-page-heading"><div><span className="kicker">{new Date().toLocaleDateString('tr-TR',{weekday:'long',day:'numeric',month:'long'})}</span><h1>{title}</h1><p>{project?'Dersini küçük adımlara böl; her adımda ilerlemeni gör.':view==='today'?'Bugün önemli olanı seç. Gerisini bir adım sonrasına bırak.':'Çalışma düzenini tek bir yerden yönet.'}</p></div><button className="button primary" onClick={()=>taskForm()}><Plus size={17}/> Yeni görev</button></header>
 {error&&<div className="study-error" role="alert"><span>{error}</span><button className="icon-button" aria-label="Hatayı kapat" onClick={()=>setError('')}><X size={15}/></button></div>}
 <div className="study-summary"><div><span>Bugünkü çalışma</span><strong>{durationText(stats.seconds)}</strong><progress value={stats.seconds/60} max={state.settings.dailyGoalMinutes} aria-label="Günlük çalışma hedefi"/><small>{state.settings.dailyGoalMinutes} dk hedef</small></div><div><span>Tamamlanan</span><strong>{stats.completed}<small> görev</small></strong><small>Bugün bitirdiğin adımlar</small></div><div><span>Açık görev</span><strong>{pending.length}</strong><small>{activeProjects.length} çalışma projesinde</small></div></div>
 {project&&<div className="study-project-tools"><button className="button ghost compact" onClick={()=>setForm({kind:'project',item:project})}><Pencil size={14}/> Projeyi düzenle</button><button className="button ghost compact" onClick={()=>setForm({kind:'folder',item:{projectId}})}><FolderPlus size={15}/> Klasör ekle</button>{folderId&&<><button className="button quiet compact" onClick={()=>setForm({kind:'folder',item:state.folders.find(f=>f.id===folderId)})}>Klasörü düzenle</button><button className="button quiet compact" onClick={()=>{if(window.confirm('Klasör kaldırılsın mı? Görevler üst klasöre taşınır.'))command('folder.delete',{id:folderId}).then(s=>{if(s)setFolderId('')})}}>Klasörü kaldır</button></>}{project.courseId&&<button className="button ghost compact" onClick={()=>onOpenCourse(project.courseId)}>Bağlı derse git <ArrowRight size={14}/></button>}<button className="button quiet compact" onClick={()=>{if(window.confirm('Proje arşivlensin mi? Görevler ve süre geçmişi korunur.'))command('project.archive',{id:project.id,archived:true}).then(s=>{if(s)navigate('archive')})}}>Projeyi arşivle</button></div>}
 {taskViews.includes(view)&&<><form className="study-quick panel" onSubmit={quickAdd}><Plus size={19}/><input ref={quickRef} aria-label="Hızlı görev adı" maxLength="240" placeholder="Aklındaki görevi ekle…" value={quick} onChange={e=>setQuick(e.target.value)}/>{!projectId&&<select aria-label="Hızlı görev projesi" value={activeProjectId} onChange={e=>setQuickProject(e.target.value)}>{activeProjects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select>}<button disabled={busy||!quick.trim()} className="button primary">Ekle</button></form>
 <div className="study-task-toolbar"><label className="search-field"><Search size={16}/><input aria-label="Görevlerde ara" placeholder="Görev, not veya etiket ara" value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="Etikete göre filtrele" value={tag} onChange={e=>setTag(e.target.value)}><option value="">Tüm etiketler</option>{tags.map(t=><option key={t}>{t}</option>)}</select><label className="study-checkbox"><input type="checkbox" checked={showDone} onChange={e=>setShowDone(e.target.checked)}/> Bitenler</label><div className="study-layout-options"><button className={'icon-button '+(layout==='list'?'active':'')} title="Liste" aria-label="Liste görünümü" onClick={()=>setLayout('list')}><LayoutList size={17}/></button><button className={'icon-button '+(layout==='board'?'active':'')} title="Pano" aria-label="Pano görünümü" onClick={()=>setLayout('board')}><ListTodo size={17}/></button></div></div>
 {view==='archive'&&state.projects.filter(p=>p.archived).map(p=><div className="study-archive-project panel" key={p.id}><strong>{p.name}</strong><button disabled={busy} className="button ghost compact" onClick={()=>command('project.archive',{id:p.id,archived:false})}>Projeyi geri al</button></div>)}
 {layout==='board'?<div className="study-board">{Object.entries(statusNames).map(([status,label])=><section key={status} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const id=e.dataTransfer.getData('text/plain');if(id)command('task.status',{id,status})}}><h3>{label}<small>{filtered.filter(t=>t.status===status).length}</small></h3>{filtered.filter(t=>t.status===status).map((t,i,list)=><div key={t.id}>{row(t,i,list)}<select aria-label={t.title+' durumu'} value={t.status} disabled={busy||t.archived||state.projects.find(p=>p.id===t.projectId)?.archived} onChange={e=>command('task.status',{id:t.id,status:e.target.value})}>{Object.entries(statusNames).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></div>)}</section>)}</div>:
 <section className="panel study-task-list">{filtered.map((t,i)=>row(t,i,filtered))}{!filtered.length&&<div className="study-empty"><Target size={32}/><h3>{query||tag?'Eşleşen görev yok':'Burada biraz yer var.'}</h3><p>{view==='today'?'Bir görevi bugüne planla veya yeni bir çalışma adımı ekle.':'Projelerini küçük, tamamlanabilir adımlara bölerek başla.'}</p><button className="button ghost" onClick={()=>taskForm()}>Görev ekle</button></div>}</section>}
 {view==='today'&&<section className="panel study-daily-note"><h3>Günün notu</h3><p>Ne öğrendin, yarına ne kalsın?</p><textarea aria-label="Günün notu" rows={3} maxLength={20000} value={dailyNote} onChange={e=>setDailyNote(e.target.value)} placeholder="Bugünü birkaç cümleyle kapat…"/><button disabled={busy} className="button ghost" onClick={()=>command('daily.note',{date:today,text:dailyNote})}>Notu kaydet</button></section>}</>}
 {view==='week'&&<><div className="study-inline study-week-nav"><button className="icon-button" aria-label="Önceki hafta" onClick={()=>setPlanDate(addDays(planDate,-7))}><ArrowLeft size={17}/></button><input aria-label="Haftayı seç" type="date" value={planDate} onChange={e=>{if(e.target.value)setPlanDate(e.target.value)}}/><button className="icon-button" aria-label="Sonraki hafta" onClick={()=>setPlanDate(addDays(planDate,7))}><ArrowRight size={17}/></button><button className="button quiet" onClick={()=>setPlanDate(today)}>Bu hafta</button></div><div className="study-week">{Array.from({length:7},(_,i)=>addDays(weekStart,i)).map(date=>{const items=state.tasks.filter(t=>!t.archived&&!state.projects.find(p=>p.id===t.projectId)?.archived&&t.plannedDate===date).sort((a,b)=>a.plannedTime.localeCompare(b.plannedTime));return <section key={date} className={'panel'+(date===today?' is-today':'')} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const id=e.dataTransfer.getData('text/plain');if(id)command('task.save',{id,plannedDate:date})}}><header><strong>{new Date(date+'T12:00:00').toLocaleDateString('tr-TR',{weekday:'short',day:'numeric',month:'short'})}</strong><small>{items.reduce((n,t)=>n+t.estimateMinutes,0)} dk plan</small></header>{items.map(t=><button draggable key={t.id} className={'study-plan-task '+t.status} onDragStart={e=>e.dataTransfer.setData('text/plain',t.id)} onClick={()=>setSelected(t.id)}><small>{t.plannedTime||'Saat serbest'} · {t.estimateMinutes} dk</small><strong>{t.title}</strong><span>{state.projects.find(p=>p.id===t.projectId)?.name}</span></button>)}<button className="button quiet compact" onClick={()=>taskForm({plannedDate:date})}><Plus size={14}/> Ekle</button></section>})}</div></>}
 {view==='reports'&&<section className="panel study-report"><div className="study-inline"><h2>Son 7 gün</h2><input aria-label="Rapor bitiş tarihi" type="date" value={reportDate} onChange={e=>{if(e.target.value)setReportDate(e.target.value)}}/></div><div className="study-chart">{Array.from({length:7},(_,i)=>addDays(reportDate,i-6)).map(date=>{const sum=dayStats(state,date,now).seconds;return <div key={date}><strong>{durationText(sum)}</strong><div className="study-chart-track"><span style={{height:Math.min(100,sum/60/state.settings.dailyGoalMinutes*100)+'%'}}/></div><small>{new Date(date+'T12:00:00').toLocaleDateString('tr-TR',{weekday:'short',day:'numeric'})}</small></div>})}</div><p className="study-hint">Sütun yüksekliği günlük hedefe göre gösterilir. Süreler yerel takvim günlerine bölünür.</p><h3>Projelere göre · seçilen 7 gün</h3>{state.projects.map(p=>{const sum=entries.filter(e=>e.projectId===p.id).reduce((n,e)=>n+Array.from({length:7},(_,i)=>secondsInDay(e,addDays(reportDate,i-6))).reduce((a,b)=>a+b,0),0);return <div className="study-report-project" key={p.id}><span><i style={{background:p.color}}/>{p.name}{p.archived?' · Arşiv':''}</span><b>{durationText(sum)}</b></div>})}<a className="button ghost" href="/api/study/export?format=csv"><Download size={16}/> Tüm süreleri CSV indir</a></section>}
 {view==='logs'&&<section className="panel study-log"><header><h2>Kaydedilen çalışmalar</h2><input aria-label="Kayıt günü" type="date" value={reportDate} onChange={e=>{if(e.target.value)setReportDate(e.target.value)}}/></header><p className="study-hint">Aktif süre, duraklatınca veya aralık bitince kayda dönüşür. Gece yarısını geçen oturumlar başladığı günde listelenir.</p>{state.entries.filter(e=>localDay(e.startedAt*1000)===reportDate).sort((a,b)=>b.startedAt-a.startedAt).map(e=>{const task=state.tasks.find(t=>t.id===e.taskId);return <article key={e.id}><div><strong>{task?.title}</strong><small>{new Date(e.startedAt*1000).toLocaleTimeString('tr-TR',{hour:'2-digit',minute:'2-digit'})} · {durationText(e.seconds)} · {e.kind==='manual'?'Elle eklendi':'Sayaç'}{e.note?' · '+e.note:''}</small></div><button className="icon-button" aria-label="Süre kaydını düzenle" onClick={()=>setEntryForm({task,entry:e})}><Pencil size={16}/></button><button className="icon-button" aria-label="Süre kaydını sil" disabled={busy} onClick={()=>{if(window.confirm('Bu süre kaydı silinsin mi?'))command('entry.delete',{id:e.id})}}><Trash2 size={16}/></button></article>})}{!state.entries.some(e=>localDay(e.startedAt*1000)===reportDate)&&<p className="study-empty">Bu gün için kaydedilmiş süre yok.</p>}</section>}
 {view==='settings'&&<SettingsPanel state={state} command={command} restore={restore}/>}</main>
 {selectedTask&&<FocusPanel key={selectedTask.id} task={selectedTask} state={state} now={now} command={command} busy={busy} onEdit={()=>taskForm(selectedTask)} onSubtask={()=>taskForm({projectId:selectedTask.projectId,parentId:selectedTask.id,folderId:selectedTask.folderId})} onEntry={()=>setEntryForm({task:selectedTask})} full={full} onFull={()=>setFull(v=>!v)} onClose={()=>{setSelected(null);setFull(false)}}/>}
 </div>{full&&error&&<div className="study-error" role="alert">{error}</div>}{form&&<StudyForm key={form.kind+(form.item?.id||'new')} {...form} state={state} courses={courses} command={command} onClose={()=>setForm(null)}/>} {entryForm&&<EntryForm {...entryForm} command={command} onClose={()=>setEntryForm(null)}/>}</div>
}
