import test from 'node:test'
import assert from 'node:assert/strict'
import { allEntries, dayStats, filterTasks, localDay, secondsInDay, timerElapsed, folderContains } from '../src/studyState.mjs'
const basic=()=>({projects:[{id:'p',archived:false}],folders:[],tasks:[{id:'a',title:'Hücre',projectId:'p',notes:'',tags:['vize'],plannedDate:'2026-09-16',dueDate:null,status:'todo',order:0}],entries:[],timer:null})
test('timer caps elapsed but paused time never grows',()=>{const timer={status:'running',startedAt:100,elapsedSeconds:20,targetSeconds:60};assert.equal(timerElapsed(timer,1000),60);assert.equal(timerElapsed({...timer,status:'paused'},1000),20)})
test('live work counted once and breaks excluded',()=>{const s=basic();s.timer={taskId:'a',status:'running',startedAt:100,elapsedSeconds:0,targetSeconds:60,phase:'focus'};s.entries=[{taskId:'a',seconds:15,startedAt:50}];assert.equal(allEntries(s,130).reduce((n,e)=>n+e.seconds,0),45);s.timer.phase='shortBreak';assert.equal(allEntries(s,130).length,1)})
test('midnight spanning session split across local days',()=>{const start=new Date('2026-09-16T23:50:00').getTime()/1000;const e={startedAt:start,seconds:1800};assert.equal(secondsInDay(e,'2026-09-16'),600);assert.equal(secondsInDay(e,'2026-09-17'),1200)})
test('today includes overdue planned tasks but filters archived and completed',()=>{const s=basic();s.tasks[0].plannedDate='2026-09-15';assert.equal(filterTasks(s,{date:'2026-09-16'}).length,1);s.tasks[0].status='done';assert.equal(filterTasks(s,{date:'2026-09-16'}).length,0);s.tasks[0].status='todo';s.projects[0].archived=true;assert.equal(filterTasks(s,{view:'all'}).length,0);assert.equal(filterTasks(s,{view:'archive'}).length,1)})
test('Turkish search and tags narrow tasks',()=>{const s=basic();assert.equal(filterTasks(s,{view:'all',query:'HÜCRE',tag:'vize'}).length,1);assert.equal(filterTasks(s,{view:'all',tag:'other'}).length,0)})
test('folder ancestry tolerates malformed loops',()=>{const folders=[{id:'a',parentId:'b'},{id:'b',parentId:'a'}];assert.equal(folderContains(folders,'b','a'),true);assert.equal(folderContains(folders,'a','missing'),false)})
test('daily stats count completion by local day',()=>{const s=basic();s.tasks[0].completedAt=new Date('2026-09-16T14:00:00').getTime()/1000;assert.equal(dayStats(s,'2026-09-16',0).completed,1);assert.equal(dayStats(s,'2026-09-17',0).completed,0)})
